application:
    env: dev
    base:
        url: http://localhost:8080/dictionaryTests/
    debug: true
    upload:
        dir: /Users/maciejo/Desktop
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
        ddl-auto: create-drop
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/mydb
        username: admin
        password: admin
        driverClassName: org.postgresql.Driver

spring:
    view:
        prefix: "/WEB-INF/pages/"
        suffix: ".jsp"